### ISSUE TITLE
Missing `count` argument.

### ISSUE THREAD

**Issue by brodeuralexis** [Hopson97/rusty-gl#1]
https://github.com/Hopson97/rusty-gl/blob/57463e7fc24b551ce551e59cd0522b003549b4ed/src/buffers.rs#L65

**Comment by Hopson97** [comment]
The purpose of that function is create a single VBO, rather than multiple.

Hence it is called `gl_gen_buffer` and not `gl_gen_buffers`, which is defined directly above
