### ISSUE TITLE
Add continuous integration testing?

### ISSUE THREAD

**Issue by dxrsz** [Hopson97/rusty-gl#2]
Hey,

Great library. I had the same idea and was about to put this together, but saw that you already beat me to it, so I'll contribute here instead. It looks like the examples aren't running anymore because of breaking glutin changes (`glutin = "*"`). I'll make a pull request for fixing the examples.

Would you be interested in adding [Travis CI](https://travis-ci.org/) (or something similar)? If you haven't before, it's free and really easy and will help mitigate these types of breakages.

**Comment by Hopson97** [comment]
Thank you for the interest! I'll see about adding Travis CI support now

**Comment by Hopson97** [comment]
I think I have it set up, not entirely sure though.

**Comment by Hopson97** [comment]
https://github.com/Hopson97/rusty-gl/blob/master/README.md Build fails :(

Not sure how to fix these "gl function was not loaded" errors.

**Comment by dxrsz** [comment]
I don't think there's any good way to prevent those panics besides just disabling the running of those example docs (`cargo test --all` executes them by default). I believe you'd otherwise have to create a glutin (or other) context and load the gl functions, which would bloat the examples. #5 will just disable running them.
